# Generated by Django 4.1.4 on 2022-12-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PlayerCategory',
        ),
        migrations.RenameModel(
            old_name='PlayerInforation',
            new_name='PlayerInformation',
        ),
    ]
