# Generated by Django 4.1.4 on 2022-12-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_category_playercategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playercategory',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='playerinformation',
            options={'verbose_name': 'Players'},
        ),
    ]
