# Generated by Django 4.1.4 on 2022-12-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_playercategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playercategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='playerinformation',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.RenameField(
            model_name='playerinformation',
            old_name='son_of',
            new_name='parentage',
        ),
        migrations.RenameField(
            model_name='playerinformation',
            old_name='qulification',
            new_name='qualification',
        ),
    ]
