# Generated by Django 4.1.4 on 2022-12-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_playercategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerCategory',
            new_name='Category',
        ),
    ]
