# Generated by Django 4.1.4 on 2022-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_playercategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinformation',
            name='email_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='playerinformation',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
