# Generated by Django 4.1.4 on 2023-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_playerinformation_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinformation',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
